### ISSUE TITLE
Apply Singleton Pattern on DBLoader.java class

### ISSUE THREAD

**Issue by gssandhu143** [gssandhu143/Cab_Booking#2]
- At the moment DBLoader is general class. 
- Apply singleton design pattern on the class.
Path - [Cab_Booking](https://github.com/gssandhu143/Cab_Booking)/Database Sql Connection/DBLoader

**Comment by yagyeshbagaya** [comment]
@gssandhu143 can you please assign  this issue to me..?

**Comment by gssandhu143** [comment]
@yagyeshbagaya I have assigned this issue to you. Thanks
